services:

  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes: 
      - mongo_db:/data/db
    ports:
      [2717:27017]
  

  api:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - mongo_db
    environment:
      PORT: 5000

volumes:
  mongo_db: {}